### ISSUE TITLE
Debugging "protection level not found for eth address"

### ISSUE THREAD

**Issue by pcowgill** [uport-project/uport-ios-sdk#14]
I'm getting this error [protection level not found for eth address](https://github.com/uport-project/uport-ios-sdk/blob/8f3686fda7996624b3c5e988aa636ba916f2b2c0/Example/Pods/UPTEthereumSigner/UPTEthereumSigner/Classes/UPTHDSigner.m#L52) while using the uPort app on iOS after scanning a QR code to apply for ETHDenver. I see the error message in the JavaScript console on the browser, and it is presumably being passed through from this SDK.

iOS 12.1 on an iPhone X
uPort app version 371 (production)

There are no error messages in the uPort app under Advanced > System Messages.

What would you recommend I try to changing to debug this?

cc @joaoaguiam @magician11

**Comment by mirceanis** [comment]
The most probable cause is that you're using an identity created before uPort used the HD key derivation.
When did you first create your identity?

To debug, try to see if the same error happens with a newly created identity.

**Comment by pcowgill** [comment]
@mirceanis I created my identity a long time ago - switching to a new identity resolved it! Thanks.
