### ISSUE TITLE
Add ethr-did resolver to iOS SDK

### ISSUE THREAD

**Issue by pelle** [uport-project/uport-ios-sdk#3]

**Comment by joshuabell** [comment]
@pelle is there a spec for this? What resources are there for completing this task?

**Comment by joshuabell** [comment]
WIP

**Comment by joshuabell** [comment]
WIP for review at: https://github.com/uport-project/uport-ios-sdk/pull/6

**Comment by mirceanis** [comment]
This was fixed by #6
