### ISSUE TITLE
jump back to own application after tap continue in uPort iOS

### ISSUE THREAD

**Issue by nowperson** [uport-project/uport-ios-sdk#4]
Is there a good way to do this ?

**Comment by popaaaandrei** [comment]
@danipralea you know a way to do this? User verifies his identity inside uPort app and would need to go back to his previous app (that asked for identity validation).

**Comment by joshuabell** [comment]
@nowperson hope you able to figure this out. I had asked the team to reach out to you to help with your issue around the time you posted. Not sure if you got connected.

FYI https://chat.uport.me/ is the best place to go to for support.
